[package]
name = "kaede"
version = "0.0.0"
description = "An extensible Tauri-based Minecraft launcher written in Vue and Rust"
authors = ["windstone"]
license = "GPL-3.0"
repository = "https://github.com/kaede-basement/kaede"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.0", features = [] }

[features]
default = ["notifications"]
# Desktop notifications.
#
# On Windows, notifications require modern WinRT (related to combase.dll),
# which does not exist on Windows 7, so we target that ancient platform with '--no-default-features'
# while defining here what exactly are 'default' features
notifications = ["dep:tauri-plugin-notification"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.8.4", features = ["protocol-asset", "macos-private-api", "image-ico", "image-png", "tray-icon"] }
tauri-plugin-log = "2"

time = "0.3"
sha1 = "0.10.6"
sha2 = "0.10.9"
md-5 = "0.10.6"
sysinfo = "0.36.1"
rayon = "1.11.0"
zip = { version = "3.0", default-features = false, features = ["deflate"] }
tokio = { version = "1", features = ["fs", "macros", "rt", "time", "io-util"] }
reqwest = { version = "0.13" }

# Non-default installed plugins
tauri-plugin-fs = { version = "2", features = ["watch"] }
tauri-plugin-dialog = "2"
# 'unsafe-headers' lets callers override forbidden headers. We need it
# to send an empty 'Origin' on the Microsoft OAuth2 token request
# to avoid the 'AADSTS90023' error
tauri-plugin-http = { version = "2.5.9", features = ["unsafe-headers"] }
# See '[features]' section above to know why this is optional
tauri-plugin-notification = { version = "2", optional = true }
tauri-plugin-os = "2"
tauri-plugin-process = "2"
tauri-plugin-upload = "2"
tauri-plugin-opener = "2"
tauri-plugin-oauth = "2"
tauri-plugin-clipboard-manager = "2"

# Modded shell plugin that allows any commands (...recipe for disaster?)
tauri-plugin-shellx = "2.0.16"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"

[profile.release]
# compile each crate as one unit instead of 16 parallel chunks
# slower build but more optimizations might be applied
codegen-units = 1
# link-time optimization across crates
lto = true
# remove debug symbols from the binary
strip = true

# Unoptimized hashing in dev builds is fucking _slow_
[profile.dev.package.sha2]
opt-level = 3

[profile.dev.package.sha1]
opt-level = 3

[profile.dev.package.md-5]
opt-level = 3

# Regular 'tauri-utils' uses ctor 0.8 that fails on Windows 7,
# but this revision uses ctor 1.0 that works on Windows 7
[patch.crates-io]
tauri-utils = { git = "https://github.com/tauri-apps/tauri", rev = "8a97d387a3a1a52f7c501762517e294d8c94e119" }
# Cap 'windows-sys' at 0.60 so that 'windows-sys' uses 'ole32.dll' instead of 'combase.dll'.
# 'combase.dll' is unavailable on Windows 7
dirs-sys = { path = "vendor/dirs-sys" }
