/*
 * Kaede, a Minecraft Launcher
 * Copyright (C) 2026  windstone <notwindstone@gmail.com> and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { fileURLToPath } from "node:url";

import { includeIgnoreFile } from "@eslint/compat";
import stylistic from "@stylistic/eslint-plugin";
import unocss from "@unocss/eslint-config/flat";
import { defineConfigWithVueTs, vueTsConfigs } from "@vue/eslint-config-typescript";
import vueRequireID from "@vue-require-id/eslint-plugin";
import { globalIgnores } from "eslint/config";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import tsDoc from "eslint-plugin-tsdoc";
import eslintPluginUnicorn from "eslint-plugin-unicorn";
import pluginVue from "eslint-plugin-vue";
import globals from "globals";

// Get an absolute path of the '.gitignore' file
const gitIgnorePath = fileURLToPath(
  new URL(".gitignore", import.meta.url),
);

export default defineConfigWithVueTs(
  // Ignore linting for every path that is specified in '.gitignore'
  includeIgnoreFile(gitIgnorePath),
  globalIgnores([
    // Ignore './src-tauri' since it contains Rust code
    "./src-tauri",
    // Ignore '__mocks__' since they contain CommonJS files
    "./src/__mocks__",
    // Ignore 'vite-env.d.ts' since it is generated by vite
    "./src/vite-env.d.ts",
    // Ignore the generated type definitions
    "./types/",
  ]),
  vueTsConfigs.recommended,
  pluginVue.configs["flat/essential"],
  // Include the recommended configuration for the Unicorn ESLint plugin
  eslintPluginUnicorn.configs.recommended,
  // Include the default configuration for the UnoCSS ESLint plugin
  unocss,

  // Overwrite ESLint configurations in the opinionated way
  {
    "languageOptions": {
      "sourceType": "module",
      "globals"   : {
        ...globals.browser,
      },
    },
    "plugins": {
      "@stylistic"        : stylistic,
      "@vue-require-id"   : vueRequireID,
      "simple-import-sort": simpleImportSort,
      "tsdoc"             : tsDoc,
    },
    "rules": {

      /* Disabled rules */
      // Not all components need multi-word names, e.g. 'Layout.vue'
      "vue/multi-word-component-names"   : ["off"],
      // Not needed since Vue 3.x
      "vue/no-multiple-template-root"    : ["off"],
      // The second argument of 'JSON#stringify' does not accept 'undefined' to save formatting
      "unicorn/no-null"                  : ["off"],
      // Not needed for fully client-side applications with no Web Workers used
      "unicorn/prefer-global-this"       : ["off"],
      // Top level await appears to be broken
      "unicorn/prefer-top-level-await"   : ["off"],
      // 'document#getElementById' is faster and easier to use
      "unicorn/prefer-query-selector"    : ["off"],
      // Requires a different compiler lib version
      "unicorn/prefer-at"                : ["off"],
      // Requires a different compiler lib version
      "unicorn/no-array-reverse"         : ["off"],
      // Requires a different compiler lib version
      "unicorn/prefer-string-replace-all": ["off"],
      // Conflicts with 'eslint@stylistic/key-spacing'
      "@stylistic/no-multi-spaces"       : ["off"],
      // Conflicts with git
      "@stylistic/linebreak-style"       : ["off"],
      // Conflicts with git
      "@stylistic/eol-last"              : ["off"],

      /* Important */
      "@stylistic/semi"              : ["error", "always"],
      "@stylistic/no-confusing-arrow": ["error", {
        "allowParens"       : true,
        "onlyOneSimpleParam": false,
      }],
      "@stylistic/no-floating-decimal"         : ["error"],
      "@stylistic/max-statements-per-line"     : ["error", { "max": 1 }],
      "@stylistic/one-var-declaration-per-line": ["error", "always"],
      "vue/block-lang"                         : ["error", {
        "script": {
          "lang": "ts",
        },
      }],
      "vue/component-api-style": ["error", ["script-setup"]],

      /* ESLint */
      "capitalized-comments": ["warn", "always"],
      "max-lines"           : ["warn", {
        "max"           : 250,
        "skipBlankLines": true,
        "skipComments"  : true,
      }],
      "no-console": "warn",

      /* TSDoc */
      "tsdoc/syntax": "warn",

      /* Simple Import Sort */
      "simple-import-sort/imports": "warn",

      // Element IDs simplify styling for plugins
      "@vue-require-id/require-id": ["warn", {
        "elements": [

          /* Layout elements */
          "header",
          "footer",
          "aside",
          "main",
          "span",
          "div",
          "nav",

          /* Text */
          "label",
          "br",
          "hr",
          "ul",
          "ol",
          "li",
          "h1",
          "h2",
          "h3",
          "h4",
          "h5",
          "h6",
          "p",

          /* Interactive */
          "button",
          "input",
          "a",

          /* Graphics/Embeds */
          "canvas",
          "iframe",
          "img",
          "svg",
          "video",
        ],
      }],

      /* TypeScript */
      "@typescript-eslint/explicit-function-return-type": ["warn"],
      "@typescript-eslint/no-unused-vars"               : ["warn"],

      /* Vue */
      "vue/attribute-hyphenation": ["warn", "always", {
        "ignore"    : [],
        "ignoreTags": [],
      }],
      "vue/component-name-in-template-casing": ["warn", "PascalCase", {
        "registeredComponentsOnly": true,
        "ignores"                 : [],
      }],
      "vue/no-duplicate-attributes": ["warn", {
        "allowCoexistClass": true,
        "allowCoexistStyle": true,
      }],
      "vue/no-unused-vars" : ["warn"],
      "vue/no-extra-parens": ["warn", "all", { "nestedBinaryExpressions": true }],
      "vue/max-len"        : ["warn", {
        "code"                     : 100,
        "ignoreComments"           : false,
        "ignoreTrailingComments"   : false,
        "ignoreHTMLAttributeValues": true,
        "ignoreHTMLTextContents"   : true,
        "ignoreUrls"               : true,
      }],

      /* Unicorn */
      "unicorn/filename-case": ["warn", {
        "cases": {
          "kebabCase" : true,
          "pascalCase": true,
        },
      }],
      "unicorn/prevent-abbreviations": ["warn"],

      /* Stylistic */
      "@stylistic/array-bracket-newline"         : ["warn", "consistent"],
      "@stylistic/array-bracket-spacing"         : ["warn", "never"],
      "@stylistic/array-element-newline"         : ["warn", "consistent"],
      "@stylistic/arrow-parens"                  : ["warn", "as-needed"],
      "@stylistic/arrow-spacing"                 : ["warn", { "before": true, "after": true }],
      "@stylistic/block-spacing"                 : ["warn", "always"],
      "@stylistic/brace-style"                   : ["warn", "1tbs"],
      "@stylistic/comma-dangle"                  : ["warn", "always-multiline"],
      "@stylistic/comma-spacing"                 : ["warn", { "before": false, "after": true }],
      "@stylistic/comma-style"                   : ["warn", "last"],
      "@stylistic/computed-property-spacing"     : ["warn", "never"],
      "@stylistic/curly-newline"                 : ["warn", { "consistent": true }],
      "@stylistic/function-call-argument-newline": ["warn", "consistent"],
      "@stylistic/function-call-spacing"         : ["warn", "never"],
      "@stylistic/generator-star-spacing"        : ["warn", "before"],
      "@stylistic/implicit-arrow-linebreak"      : ["warn", "beside"],
      "@stylistic/indent"                        : ["warn", 2, { "SwitchCase": 1 }],
      "@stylistic/indent-binary-ops"             : ["warn", 2],
      "@stylistic/key-spacing"                   : ["warn", {
        "beforeColon": false,
        "afterColon" : true,
        "mode"       : "strict",
        "align"      : {
          "beforeColon": false,
          "afterColon" : true,
          "on"         : "colon",
          "mode"       : "strict",
        },
      }],
      "@stylistic/keyword-spacing"      : ["warn", { "before": true, "after": true }],
      "@stylistic/line-comment-position": ["warn", { "position": "above" }],
      "@stylistic/lines-around-comment" : ["warn", {
        "beforeBlockComment": true,
        "allowBlockStart"   : true,
      }],
      "@stylistic/lines-between-class-members": ["warn", "always", {
        "exceptAfterOverload"  : true,
        "exceptAfterSingleLine": true,
      }],
      "@stylistic/member-delimiter-style": ["warn", {
        "multiline": {
          "delimiter"  : "semi",
          "requireLast": true,
        },
        "singleline": {
          "delimiter"  : "semi",
          "requireLast": false,
        },
        "multilineDetection": "brackets",
      }],
      "@stylistic/multiline-comment-style" : ["warn", "starred-block"],
      "@stylistic/new-parens"              : ["warn", "never"],
      "@stylistic/newline-per-chained-call": ["warn", { "ignoreChainWithDepth": 2 }],
      "@stylistic/no-extra-semi"           : ["warn"],
      "@stylistic/no-mixed-operators"      : ["warn", {
        "groups": [
          ["+", "-", "*", "/", "%", "**"],
          ["&", "|", "^", "~", "<<", ">>", ">>>"],
          ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
          ["&&", "||"],
          ["in", "instanceof"],
        ],
        "allowSamePrecedence": true,
      }],
      "@stylistic/no-mixed-spaces-and-tabs"        : ["warn"],
      "@stylistic/no-multiple-empty-lines"         : ["warn", { "max": 3, "maxEOF": 1 }],
      "@stylistic/no-tabs"                         : ["warn"],
      "@stylistic/no-trailing-spaces"              : ["warn"],
      "@stylistic/no-whitespace-before-property"   : ["warn"],
      "@stylistic/nonblock-statement-body-position": ["warn", "beside"],
      "@stylistic/object-curly-newline"            : ["warn", { "consistent": true }],
      "@stylistic/object-curly-spacing"            : ["warn", "always"],
      "@stylistic/padded-blocks"                   : ["warn", "never"],
      "@stylistic/padding-line-between-statements" : [
        "warn",
        { "blankLine": "always", "prev": "*", "next": "return" },
        { "blankLine": "always", "prev": ["const", "let", "var"], "next": "*" },
        { "blankLine": "any", "prev": ["const", "let", "var"], "next": ["const", "let", "var"] },
        { "blankLine": "always", "prev": "directive", "next": "*" },
        { "blankLine": "any", "prev": "directive", "next": "directive" },
      ],
      "@stylistic/quote-props"                : ["warn", "always"],
      "@stylistic/quotes"                     : ["warn", "double"],
      "@stylistic/rest-spread-spacing"        : ["warn"],
      "@stylistic/semi-spacing"               : ["warn", { "before": false, "after": true }],
      "@stylistic/semi-style"                 : ["warn", "last"],
      "@stylistic/space-before-blocks"        : ["warn", "always"],
      "@stylistic/space-before-function-paren": ["warn", {
        "anonymous" : "always",
        "named"     : "never",
        "asyncArrow": "always",
        "catch"     : "always",
      }],
      "@stylistic/space-in-parens"         : ["warn", "never"],
      "@stylistic/space-unary-ops"         : ["warn", { "words": true, "nonwords": false }],
      "@stylistic/spaced-comment"          : ["warn", "always"],
      "@stylistic/switch-colon-spacing"    : ["warn", { "after": true, "before": false }],
      "@stylistic/template-curly-spacing"  : ["warn", "never"],
      "@stylistic/template-tag-spacing"    : ["warn", "never"],
      "@stylistic/type-generic-spacing"    : ["warn"],
      "@stylistic/type-named-tuple-spacing": ["warn"],
      "@stylistic/wrap-iife"               : ["warn", "inside"],
      "@stylistic/wrap-regex"              : ["warn"],
      "@stylistic/yield-star-spacing"      : ["warn", { "before": false, "after": true }],
    },
  },
);
