/*
 * Kaede, a Minecraft Launcher
 * Copyright (C) 2026  windstone <notwindstone@gmail.com> and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import ExtensionsManager from "@/lib/extensions-manager";
import type { ServerProcessType } from "@/types/application/server-process.type.ts";

type LightResponse<T> = Promise<T> | T;
type GetCallback = (request: { "params": Record<string, unknown> }) => LightResponse<unknown>;
type PostCallback = (request: {
  "body"  : unknown;
  "params": Record<string, unknown>;
}) => LightResponse<unknown>;

export default class Txiki {
  private paths: {
    "GET" : Map<string, string>;
    "POST": Map<string, string>;
  } = {
    "GET" : new Map,
    "POST": new Map,
  };

  private serializeRoutes(map: Map<string, string>): string {
    if (map.size === 0) {
      return "{}";
    }

    const entries: Array<string> = [];

    for (const [path, callback] of map) {
      entries.push(`${JSON.stringify(path)}: ${callback}`);
    }

    return `{\n${entries.join(",\n")}\n}`;
  }

  public get(path: string, callback: GetCallback): Txiki {
    this.paths.GET.set(path, callback.toString());

    return this;
  }

  public post(path: string, callback: PostCallback): Txiki {
    this.paths.POST.set(path, callback.toString());

    return this;
  }

  public async listen(port: number): Promise<ServerProcessType | undefined> {
    const name: string = `txiki-${port}`;
    const getRoutes = this.serializeRoutes(this.paths.GET);
    const postRoutes = this.serializeRoutes(this.paths.POST);
    const code = `
// Auto-generated by Kaede
const routes = {
  GET: ${getRoutes},
  POST: ${postRoutes},
};

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const method = request.method;
    const handlerMap = routes[method];

    if (!handlerMap) {
      return new Response("Method Not Allowed", { status: 405 });
    }

    const handler = handlerMap[url.pathname];

    if (!handler) {
      return new Response("Not Found", { status: 404 });
    }

    try {
      // Build params from query string
      const params = {};
      url.searchParams.forEach((v, k) => { params[k] = v; });

      if (method === "POST") {
        // Read body as JSON or plain text
        const contentType = request.headers.get("content-type") || "";
        let body;
        if (contentType.includes("application/json")) {
          body = await request.json();
        } else {
          body = await request.text();
        }
        console.log("Executing the POST callback...");
        const result = await handler({ body, params });
        console.log("The result of a POST callback:", result);
        return toResponse(result);
      } else {
        // GET
        console.log("Executing the GET callback...");
        const result = await handler({ params });
        console.log("The result of a GET callback:", result);
        return toResponse(result);
      }
    } catch (err) {
      console.error("Handler error:", err);
      return new Response("Internal Server Error", { status: 500 });
    }
  },
};

// Helper to turn handler return values into proper Response objects
function toResponse(data) {
  if (data instanceof Response) return data;
  if (typeof data === "string") return new Response(data);
  return new Response(JSON.stringify(data), {
    headers: { "Content-Type": "application/json" },
  });
}
`.trim();

    return await ExtensionsManager.serveCode(name, code, port);
  }
}
