name: 'Build'

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - flake.lock
    branches:
      - nightly
      - beta
      - rc
      - release

jobs:
  tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "macOS-ARM"
            platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - name: "macOS-x86_64"
            platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - name: "Linux"
            platform: 'ubuntu-22.04'
            args: ''
          - name: "Windows"
            platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out a repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: bun install

      - name: Build a Tauri app (Nightly)
        if: github.ref == 'refs/heads/nightly'
        uses: tauri-apps/tauri-action@v0
        with:
          appName: 'App v__VERSION__'
          args: ${{ matrix.args }}

      - name: Build a Tauri app (Non-Nightly)
        if: github.ref != 'refs/heads/nightly'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: Temporary
        run: |
          ls

      - name: Upload binary (Windows, NSIS)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'windows-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: 'kaede-nightly-windows-nsis'
          path: './src-tauri/target/release/bundle/nsis/kaede_0.1.0_x64-setup.exe'

      - name: Upload binary (Windows, MSI)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'windows-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: 'kaede-nightly-windows-msi'
          path: './src-tauri/target/release/bundle/msi/kaede_0.1.0_x64_en-US.msi'

      - name: Upload binary (Linux, DEB)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'ubuntu-22.04')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: 'kaede-nightly-linux-deb'
          path: './src-tauri/target/release/bundle/deb/kaede_0.1.0_amd64.deb'

      - name: Upload binary (Linux, RPM)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'ubuntu-22.04')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: 'kaede-nightly-linux-rpm'
          path: './src-tauri/target/release/bundle/rpm/kaede-0.1.0-1.x86_64.rpm'

      - name: Upload binary (Linux, AppImage)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'ubuntu-22.04')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: 'kaede-nightly-linux-app-image'
          path: './src-tauri/target/release/bundle/appimage/kaede_0.1.0_amd64.AppImage'

      - name: Upload binary (macOS, x86_64, DMG)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'macos-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: 'kaede-nightly-macos-x86_64-dmg'
          path: './src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/kaede_0.1.0_x64.dmg'

      - name: Upload binary (macOS, x86_64, tarball)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'macos-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: 'kaede-nightly-macos-x86_64-tarball'
          path: './src-tauri/target/x86_64-apple-darwin/release/bundle/macos/kaede.app.tar.gz'

      - name: Upload binary (macOS, ARM, DMG)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'macos-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: 'kaede-nightly-macos-arm-dmg'
          path: './src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/kaede_0.1.0_aarch64.dmg'

      - name: Upload binary (macOS, ARM, tarball)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'macos-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: 'kaede-nightly-macos-arm-tarball'
          path: './src-tauri/target/aarch64-apple-darwin/release/bundle/macos/kaede.app.tar.gz'
