name: 'Build'

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - flake.lock
    branches:
      - nightly
    tags:
      - "*"
  workflow_dispatch:

jobs:
  tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "macOS-ARM"
            platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - name: "macOS-x86_64"
            platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - name: "Linux"
            platform: 'ubuntu-22.04'
            args: ''
          - name: "Windows"
            platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out a repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Bump tauri.conf.json version (Non-Nightly)
        if: github.ref != 'refs/heads/nightly'
        uses: restackio/update-json-file-action@2.1
        with:
          file: "./src-tauri/tauri.conf.json"
          fields: "{\"version\": \"${{ github.event.base_ref }}\"}"

      - name: Bump Cargo.toml version (Non-Nightly)
        if: github.ref != 'refs/heads/nightly'
        uses: tj-actions/cargo-bump@v3
        with:
          working-directory: './src-tauri/'

      - name: Install frontend dependencies
        run: bun install

      - name: Build a Tauri app (Nightly)
        if: github.ref == 'refs/heads/nightly'
        uses: tauri-apps/tauri-action@v0
        with:
          appName: 'App v__VERSION__'
          args: ${{ matrix.args }}

      - name: Build a Tauri app (Non-Nightly)
        if: github.ref != 'refs/heads/nightly'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: ${{ github.ref != 'refs/heads/release' }}
          args: ${{ matrix.args }}

      - name: Get current build info
        id: json_properties
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "./src-tauri/tauri.conf.json"

      - name: Upload binary (Windows, NSIS)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'windows-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-windows-nsis-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/release/bundle/nsis/${{ steps.json_properties.outputs.productName }}_${{steps.json_properties.outputs.version}}_x64-setup.exe'

      - name: Upload binary (Windows, MSI)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'windows-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-windows-msi-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/release/bundle/msi/${{ steps.json_properties.outputs.productName }}_${{steps.json_properties.outputs.version}}_x64_en-US.msi'

      - name: Upload binary (Windows, portable)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'windows-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-windows-portable-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/release/${{ steps.json_properties.outputs.productName }}.exe'

      - name: Upload binary (Linux, DEB)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'ubuntu-22.04')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-linux-deb-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/release/bundle/deb/${{ steps.json_properties.outputs.productName }}_${{steps.json_properties.outputs.version}}_amd64.deb'

      - name: Upload binary (Linux, RPM)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'ubuntu-22.04')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-linux-rpm-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/release/bundle/rpm/${{ steps.json_properties.outputs.productName }}-${{steps.json_properties.outputs.version}}-1.x86_64.rpm'

      - name: Upload binary (Linux, AppImage)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'ubuntu-22.04')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-linux-app-image-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/release/bundle/appimage/${{ steps.json_properties.outputs.productName }}_${{steps.json_properties.outputs.version}}_amd64.AppImage'

      - name: Upload binary (macOS, x86_64, DMG)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'macos-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-macos-x86_64-dmg-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/${{ steps.json_properties.outputs.productName }}_${{steps.json_properties.outputs.version}}_x64.dmg'

      - name: Upload binary (macOS, x86_64, tarball)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'macos-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-macos-x86_64-tarball-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/x86_64-apple-darwin/release/bundle/macos/${{ steps.json_properties.outputs.productName }}.app.tar.gz'

      - name: Upload binary (macOS, ARM, DMG)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'macos-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-macos-arm-dmg-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/${{ steps.json_properties.outputs.productName }}_${{steps.json_properties.outputs.version}}_aarch64.dmg'

      - name: Upload binary (macOS, ARM, tarball)
        if: (github.ref == 'refs/heads/nightly' && matrix.platform == 'macos-latest')
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'warn'
          name: '${{ steps.json_properties.outputs.productName }}-nightly-macos-arm-tarball-${{steps.json_properties.outputs.version}}-${{ github.ref }}'
          path: './src-tauri/target/aarch64-apple-darwin/release/bundle/macos/${{ steps.json_properties.outputs.productName }}.app.tar.gz'
